### ISSUE TITLE
Browser based streaming audio skips when starting due to a buffering error

### ISSUE THREAD

**Issue by SpikedRN** [CyanogenMod/android_device_motorola_surnia#1]
When starting playback of audio streams in the browser on sites such as Bandcamp or Soundcloud, the audio will skip for several seconds, and it will not play normally unless you seek back to the beginning of the track. The problem will repeat when the next track starts. Reducing the size of audio.offload.buffer.size.kb from the default of 240kb to 120kb causes the audio stream to playback correctly without any buffering errors.

**Comment by ramsudharsan** [comment]
64kb seems to be the ideal buffer size than 120kb or 240kb

**Comment by ramsudharsan** [comment]
@SpikedRN http://review.cyanogenmod.org/#/c/122278/

**Comment by ramsudharsan** [comment]
I didn't notice that pull request until just now (i.e https://github.com/SpikedRN/android_device_motorola_surnia/commit/1b285368f8c1d27321abc5ba4d39b9f06f364307 ) Sorry for that

**Comment by SpikedRN** [comment]
I will test with the buffer set to 64kb and see if it works ok.

**Comment by SpikedRN** [comment]
Working good here with the buffer at 64kb.

**Comment by ramsudharsan** [comment]
Thanks for testing this :+1:
